name: publish node binary
on:
  push:
    branches: ["ci"]
jobs:
  publish:
    strategy:
      fail-fast: true
    name: publish
    runs-on: ubuntu-20.04
    steps:
      - uses: dtolnay/rust-toolchain@1.66.1
        with:
          components: rustfmt

######## CACHE ########
      - name: system packages
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: build-essential ca-certificates clang curl git libpq-dev libssl-dev pkg-config lsof lld libgmp-dev
          version: 1.0


      - name: checkout
        uses: actions/checkout@v3

      - name: caching
        uses: Swatinem/rust-cache@v2
        with:
          cache-all-crates: true
          cache-on-failure: true

      - name: mtime restore (not sure this does anything)
        uses: chetan/git-restore-mtime-action@v2

######## BUILD ########

      - name: cargo release build
        run: cargo b --release -p aptos-node


