name: node bin
on:
  push:
    tags:
     - v[0-9]+.*
jobs:
  publish:
    # needs: heat
    strategy:
      fail-fast: true
    name: publish
    runs-on: ubuntu-20.04
    steps:
      - uses: dtolnay/rust-toolchain@1.66.1
        with:
          components: rustfmt

######## CACHE ########
      - name: system packages
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: build-essential ca-certificates clang curl git libpq-dev libssl-dev pkg-config lsof lld libgmp-dev
          version: 1.0

      - name: checkout
        uses: actions/checkout@v3

      - name: caching
        uses: Swatinem/rust-cache@v2
        with:
          prefix-key: "v1"
          shared-key: "zapatos" # to share across CI builds, so it is not job-id specific
          cache-on-failure: true

      - name: cargo release build
        run: cargo b --release -p aptos-node

######## PUBLISH ########

      - name: publish
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/aptos-node
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
