# testing future versions of rust
name: rust-versions
on:
  push:
    branches: ["*"] # glob pattern to allow slash /
  schedule:
    - cron: "30 00 * * *"

jobs:
  builds:
    strategy:
      matrix:
        channel: ["stable", "beta"]
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4

      - name: setup env
        uses: ./.github/actions/build_env

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{matrix.channel}}
          override: true

      - name: does it build?
        run: cargo check
