name: rust-build

on:
  push:
    branches:
      - release
      - "ci*"
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - release

jobs:
  builds:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: setup env
        uses: ./.github/actions/build_env

      - name: Run cargo build for default packages
        run:  cargo build
